### ISSUE TITLE
Python issue, workaround?

### ISSUE THREAD

**Issue by Silence720** [ZeliardM/homebridge-kasa-python#40]
**Describe The Bug:**
I am using homebridge via windows and continue to get the python verision message as it is running 3.8. Is there a workaround?  I am assuming running on a docker container? Thank you.

**Comment by ZeliardM** [comment]
@Silence720 You could use docker. Python 3.13 is available for Windows to install, but I'm not sure your setup exactly. Are you running Homebridge installed on Windows as a Service? Or are you using the Hyper-V Image?

**Comment by Silence720** [comment]
I am currently using homebridge via windows hyper-v. I have also tried as a service and get the same message. My machine has python 3.13 installed.  Thank you.

**Comment by ZeliardM** [comment]
@Silence720 The Hyper-V image may not have the latest version. would probably be better to use a VM with ubuntu and run Homebridge in Docker to resolve.

**Comment by Mizokuiam** [comment]
Hey @Silence720,

I've seen similar issues before with Python versions and Homebridge on Windows, especially when using Hyper-V.  The problem stems from the Hyper-V image likely having an older, embedded Python version that clashes with your system's Python 3.13.  While having 3.13 installed on your *host* machine is great, the Homebridge instance *inside* the Hyper-V environment is isolated and uses its own pre-installed Python.

As @ZeliardM mentioned, switching to a Dockerized setup within a full Ubuntu VM (not the limited Hyper-V image) is the cleanest and most reliable way forward. This lets you control the exact Python version used by Homebridge *and* removes the version conflict woes you're experiencing.

Here's a step-by-step guide on how to set this up:

1. **Install a VM:** Install a Virtual Machine software like VirtualBox or VMware Workstation Player (both free).  I personally prefer VirtualBox for its simplicity.

2. **Set up Ubuntu:** Download the latest Ubuntu Server ISO (desktop version works too, but server is lighter) and create a new VM with it. Allocate sufficient resources (at least 2GB RAM and 20GB disk space).

3. **Install Docker and Docker Compose:** After Ubuntu is installed and updated (`sudo apt update && sudo apt upgrade`), install Docker and Docker Compose:

   ```bash
   sudo apt install docker.io docker-compose-plugin
   sudo groupadd docker  # Add docker group
   sudo usermod -aG docker $USER # Add your user to the docker group
   newgrp docker # Refresh group membership (or log out and back in)
   ```

4. **Create a `docker-compose.yml` file:**  This file will orchestrate Homebridge and define its environment. Create a file named `docker-compose.yml` in a dedicated directory for your Homebridge setup with the following content:

   ```yaml
   version: "3.7"
   services:
     homebridge:
       image: oznu/homebridge:latest # or a specific version if desired
       container_name: homebridge
       restart: always
       ports:
         - "8581:8581" # Adjust if necessary
         - "51826:51826" # Adjust if necessary
       volumes:
         - ./config:/config # Maps your local config to the container
         - /var/run/docker.sock:/var/run/docker.sock # Optional: for easier plugin install within container
       environment:
         - HOMEBRIDGE_CONFIG_UI_PORT=8080 # Adjust if necessary
         - TZ=America/Your_Timezone # Set your timezone
       devices:  #  Important for accessing USB devices, if needed for some plugins
         - /dev/ttyUSB0:/dev/ttyUSB0 # Example - modify based on your devices
     homebridge-kasa-python:
        image: zeliardm/homebridge-kasa-python:latest
        container_name: homebridge-kasa-python
        depends_on:
          - homebridge
        environment:
          - HOMEBRIDGE_USERNAME=<your homebridge username>
          - HOMEBRIDGE_PASSWORD=<your homebridge password>
          - HOMEBRIDGE_PIN=<your homebridge pin>
          - KASA_USERNAME=<your kasa username>
          - KASA_PASSWORD=<your kasa password>
   ```

5. **Configure Homebridge:**  Create a `config.json` file in the same directory as your `docker-compose.yml`. The initial configuration can be empty: `{}`. After starting Homebridge, you can configure plugins through the web UI (typically at `http://<your_vm_ip>:8080`).


6. **Run Homebridge:** In the directory with your `docker-compose.yml`, run:

   ```bash
   docker-compose up -d
   ```


This setup ensures that your `homebridge-kasa-python` plugin runs correctly within a controlled environment with the latest Python version provided by the Docker image. You can easily update both Homebridge and the plugin by pulling newer images with `docker-compose pull` followed by `docker-compose up -d`.

This approach avoids the complexities of managing Python versions on Windows and provides a much more robust and predictable environment for Homebridge.
